CREATE USER IF NOT EXISTS moringa_app WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
GRANT CONNECT ON DATABASE moringa TO moringa_app;
GRANT USAGE ON SCHEMA public TO moringa_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO moringa_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO moringa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO moringa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO moringa_app;
REVOKE CREATE ON SCHEMA public FROM moringa_app;
REVOKE DROP ON SCHEMA public FROM moringa_app;
