/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

export * as new_arrivals from "./new_arrivals/index";
export * as hero from "./hero/index";
export * as health from "./health/index";
export * as gift_card from "./gift_card/index";
export * as coupon from "./coupon/index";
export * as cart from "./cart/index";

/**
 * @controller AppController.root
 * @path GET /
 * @accessor api.functional.root
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function root(connection: IConnection): Promise<root.Output> {
  return PlainFetcher.fetch(connection, {
    ...root.METADATA,
    template: root.METADATA.path,
    path: root.path(),
  });
}
export namespace root {
  export type Output = Primitive<{
    status: string;
    app: string;
    version: string;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/";
}
