/**
 * @packageDocumentation
 * @module api.functional.gift_card
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";

import type { CreateGiftCardDto } from "../../../../../../apps/moringa-backend/src/gift-card/dto/create-gift-card.dto";
import type { UpdateGiftCardDto } from "../../../../../../apps/moringa-backend/src/gift-card/dto/update-gift-card.dto";

/**
 * @controller GiftCardController.redeem
 * @path POST /gift-card/redeem
 * @accessor api.functional.gift_card.redeem
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function redeem(
  connection: IConnection,
  props: redeem.Props,
): Promise<redeem.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...redeem.METADATA,
      template: redeem.METADATA.path,
      path: redeem.path(),
    },
    props.dto,
  );
}
export namespace redeem {
  export type Props = { dto: Body };
  export type Body = Primitive<{ code: string }>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "POST",
    path: "/gift-card/redeem",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/gift-card/redeem";
}

/**
 * @controller GiftCardController.balance
 * @path GET /gift-card/balance
 * @accessor api.functional.gift_card.balance
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function balance(
  connection: IConnection,
  props: balance.Props,
): Promise<balance.Output> {
  return PlainFetcher.fetch(connection, {
    ...balance.METADATA,
    template: balance.METADATA.path,
    path: balance.path(props),
  });
}
export namespace balance {
  export type Props = { query: Query };
  export type Query = Resolved<{ code: string }>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/gift-card/balance",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(props.query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/gift-card/balance";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller GiftCardController.findAll
 * @path GET /gift-card
 * @accessor api.functional.gift_card.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/gift-card",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/gift-card";
}

/**
 * @controller GiftCardController.findOne
 * @path GET /gift-card/:id
 * @accessor api.functional.gift_card.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  props: findOne.Props,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(props),
  });
}
export namespace findOne {
  export type Props = { id: number };
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/gift-card/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/gift-card/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}

/**
 * @controller GiftCardController.create
 * @path POST /gift-card
 * @accessor api.functional.gift_card.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    props.dto,
  );
}
export namespace create {
  export type Props = { dto: Body };
  export type Body = Primitive<CreateGiftCardDto>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "POST",
    path: "/gift-card",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/gift-card";
}

/**
 * @controller GiftCardController.update
 * @path PATCH /gift-card/:id
 * @accessor api.functional.gift_card.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(props),
    },
    props.dto,
  );
}
export namespace update {
  export type Props = { id: number; dto: Body };
  export type Body = Primitive<UpdateGiftCardDto>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "PATCH",
    path: "/gift-card/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "dto">) =>
    `/gift-card/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}

/**
 * @controller GiftCardController.remove
 * @path DELETE /gift-card/:id
 * @accessor api.functional.gift_card.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(props),
  });
}
export namespace remove {
  export type Props = { id: number };
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "DELETE",
    path: "/gift-card/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/gift-card/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}
