bind 127.0.0.1

port 6379

dir /var/lib/redis

daemonize no

protected-mode yes

save ""

appendonly no

lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
