/**
 * @packageDocumentation
 * @module api.functional.cart
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

/**
 * @controller CartController.create
 * @path POST /cart
 * @accessor api.functional.cart.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    props.dto,
  );
}
export namespace create {
  export type Props = { dto: Body };
  export type Body = Primitive<{ productId: number; quantity?: number }>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "POST",
    path: "/cart",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/cart";
}

/**
 * @controller CartController.findAll
 * @path GET /cart
 * @accessor api.functional.cart.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/cart",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/cart";
}

/**
 * @controller CartController.remove
 * @path DELETE /cart/:id
 * @accessor api.functional.cart.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(props),
  });
}
export namespace remove {
  export type Props = { id: string };
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "DELETE",
    path: "/cart/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/cart/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}
