/**
 * @packageDocumentation
 * @module api.functional.coupon
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { CreateCouponDto } from "../../../../../../apps/moringa-backend/src/coupon/dto/create-coupon.dto";

export * as analytics from "./analytics/index";

/**
 * @controller CouponController.validate
 * @path POST /coupon/validate
 * @accessor api.functional.coupon.validate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function validate(
  connection: IConnection,
  props: validate.Props,
): Promise<validate.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...validate.METADATA,
      template: validate.METADATA.path,
      path: validate.path(),
    },
    props.body,
  );
}
export namespace validate {
  export type Props = { body: Body };
  export type Body = Primitive<{
    code: string;
    orderValue: number;
    userId?: number;
  }>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "POST",
    path: "/coupon/validate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/coupon/validate";
}

/**
 * @controller CouponController.findAll
 * @path GET /coupon
 * @accessor api.functional.coupon.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/coupon",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/coupon";
}

/**
 * @controller CouponController.create
 * @path POST /coupon
 * @accessor api.functional.coupon.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    props.dto,
  );
}
export namespace create {
  export type Props = { dto: Body };
  export type Body = Primitive<CreateCouponDto>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "POST",
    path: "/coupon",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/coupon";
}

/**
 * @controller CouponController.update
 * @path PATCH /coupon/:id
 * @accessor api.functional.coupon.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(props),
    },
    props.dto,
  );
}
export namespace update {
  export type Props = { id: number; dto: Body };
  export type Body = Primitive<CreateCouponDto>;
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "PATCH",
    path: "/coupon/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "dto">) =>
    `/coupon/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}

/**
 * @controller CouponController.remove
 * @path DELETE /coupon/:id
 * @accessor api.functional.coupon.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  props: remove.Props,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(props),
  });
}
export namespace remove {
  export type Props = { id: number };
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "DELETE",
    path: "/coupon/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (props: Props) =>
    `/coupon/${encodeURIComponent(props.id?.toString() ?? "null")}`;
}
