-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "codAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "handlingAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "shippingType" TEXT;

-- AlterTable
ALTER TABLE "StoreSettings" ADD COLUMN     "codCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "expressShippingCharge" DOUBLE PRECISION NOT NULL DEFAULT 149,
ADD COLUMN     "handlingCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sameDayShippingCharge" DOUBLE PRECISION NOT NULL DEFAULT 249,
ADD COLUMN     "shippingOptions" JSONB;
