/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { HealthResponse } from "../../../../../../apps/moringa-backend/src/health/health.controller";

/**
 * @controller HealthController.check
 * @path GET /health
 * @accessor api.functional.health.check
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check(connection: IConnection): Promise<check.Output> {
  return PlainFetcher.fetch(connection, {
    ...check.METADATA,
    template: check.METADATA.path,
    path: check.path(),
  });
}
export namespace check {
  export type Output = Primitive<HealthResponse>;

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
}

/**
 * @controller HealthController.ready
 * @path GET /health/ready
 * @accessor api.functional.health.ready
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function ready(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...ready.METADATA,
    template: ready.METADATA.path,
    path: ready.path(),
  });
}
export namespace ready {
  export const METADATA = {
    method: "GET",
    path: "/health/ready",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health/ready";
}

/**
 * @controller HealthController.live
 * @path GET /health/live
 * @accessor api.functional.health.live
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function live(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...live.METADATA,
    template: live.METADATA.path,
    path: live.path(),
  });
}
export namespace live {
  export const METADATA = {
    method: "GET",
    path: "/health/live",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health/live";
}
