/**
 * @packageDocumentation
 * @module api.functional.coupon.analytics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

/**
 * @controller CouponController.getAnalytics
 * @path GET /coupon/analytics
 * @accessor api.functional.coupon.analytics.getAnalytics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAnalytics(
  connection: IConnection,
): Promise<getAnalytics.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAnalytics.METADATA,
    template: getAnalytics.METADATA.path,
    path: getAnalytics.path(),
  });
}
export namespace getAnalytics {
  export type Output = Primitive<unknown>;

  export const METADATA = {
    method: "GET",
    path: "/coupon/analytics",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/coupon/analytics";
}
